apiVersion: v1
kind: Service
metadata:
  name: k8gobgp-webhook-service
  namespace: k8gobgp-system
  labels:
    app.kubernetes.io/name: k8gobgp
    app.kubernetes.io/component: webhook
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: k8gobgp
    app.kubernetes.io/component: controller
