apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8gobgp-manager-rolebinding
  labels:
    app.kubernetes.io/name: k8gobgp
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: k8gobgp-controller-manager
  namespace: k8gobgp-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8gobgp-manager-role
