apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gobgp-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: gobgp-controller-manager
  namespace: gobgp-system # Must match the namespace of the ServiceAccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8gobgp-manager-role
