apiVersion: bgp.purelb.io/v1
kind: BGPConfiguration
metadata:
  name: global-bgp-config
  namespace: k8gobgp-system
spec:
  global:
    asn: 64512
    routerID: "192.168.0.1"
  neighbors:
    - config:
        neighborAddress: "192.168.151.161"
        peerAsn: 65413
      afiSafis:
        - family: "ipv4-unicast"
          enabled: true
