---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: bgpconfigurations.bgp.example.com
spec:
  group: bgp.example.com
  names:
    kind: BGPConfiguration
    listKind: BGPConfigurationList
    plural: bgpconfigurations
    singular: bgpconfiguration
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              dynamicNeighbors:
                items:
                  properties:
                    peerGroup:
                      type: string
                    prefix:
                      type: string
                  required:
                  - peerGroup
                  - prefix
                  type: object
                type: array
              global:
                properties:
                  applyPolicy:
                    properties:
                      exportPolicy:
                        properties:
                          defaultAction:
                            type: string
                          direction:
                            type: string
                          name:
                            type: string
                          policies:
                            items:
                              type: string
                            type: array
                        type: object
                      importPolicy:
                        properties:
                          defaultAction:
                            type: string
                          direction:
                            type: string
                          name:
                            type: string
                          policies:
                            items:
                              type: string
                            type: array
                        type: object
                      inPolicy:
                        properties:
                          defaultAction:
                            type: string
                          direction:
                            type: string
                          name:
                            type: string
                          policies:
                            items:
                              type: string
                            type: array
                        type: object
                    type: object
                  asn:
                    format: int32
                    type: integer
                  bindToDevice:
                    type: string
                  confederation:
                    properties:
                      enabled:
                        type: boolean
                      identifier:
                        format: int32
                        type: integer
                      memberAsList:
                        items:
                          format: int32
                          type: integer
                        type: array
                    type: object
                  defaultRouteDistance:
                    properties:
                      externalRouteDistance:
                        format: int32
                        type: integer
                      internalRouteDistance:
                        format: int32
                        type: integer
                    type: object
                  families:
                    items:
                      format: int32
                      type: integer
                    type: array
                  gracefulRestart:
                    properties:
                      deferralTime:
                        format: int32
                        type: integer
                      enabled:
                        type: boolean
                      helperOnly:
                        type: boolean
                      mode:
                        type: string
                      restartTime:
                        format: int32
                        type: integer
                    type: object
                  listenAddresses:
                    items:
                      type: string
                    type: array
                  listenPort:
                    format: int32
                    type: integer
                  routeSelectionOptions:
                    properties:
                      advertiseInactiveRoutes:
                        type: boolean
                      alwaysCompareMed:
                        type: boolean
                      enableAigp:
                        type: boolean
                      externalCompareRouterId:
                        type: boolean
                      ignoreAsPathLength:
                        type: boolean
                      ignoreNextHopIgpMetric:
                        type: boolean
                    type: object
                  routerID:
                    type: string
                  useMultiplePaths:
                    type: boolean
                required:
                - asn
                - routerID
                type: object
              neighbors:
                items:
                  properties:
                    config:
                      properties:
                        adminDown:
                          type: boolean
                        allowOwnAsn:
                          format: int32
                          type: integer
                        authPassword:
                          type: string
                        description:
                          type: string
                        localAsn:
                          format: int32
                          type: integer
                        neighborAddress:
                          type: string
                        neighborInterface:
                          type: string
                        peerAsn:
                          format: int32
                          type: integer
                        peerGroup:
                          type: string
                        peerType:
                          type: string
                        removePrivate:
                          type: string
                        replacePeerAsn:
                          type: boolean
                        routeFlapDamping:
                          type: boolean
                        sendCommunity:
                          format: int32
                          type: integer
                        vrf:
                          type: string
                      required:
                      - neighborAddress
                      - peerAsn
                      type: object
                  required:
                  - config
                  type: object
                type: array
              peerGroups:
                items:
                  properties:
                    config:
                      properties:
                        authPassword:
                          type: string
                        description:
                          type: string
                        localAsn:
                          format: int32
                          type: integer
                        peerAsn:
                          format: int32
                          type: integer
                        peerGroupName:
                          type: string
                        peerType:
                          type: string
                        removePrivate:
                          type: string
                        routeFlapDamping:
                          type: boolean
                        sendCommunity:
                          format: int32
                          type: integer
                      required:
                      - peerGroupName
                      type: object
                  required:
                  - config
                  type: object
                type: array
              vrfs:
                items:
                  properties:
                    exportRt:
                      items:
                        type: string
                      type: array
                    id:
                      format: int32
                      type: integer
                    importRt:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    rd:
                      type: string
                  required:
                  - name
                  type: object
                type: array
            required:
            - global
            type: object
          status:
            properties:
              observedGeneration:
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
